### ISSUE TITLE
passing qsub/sbatch parameters to individual make rules.

### ISSUE THREAD

**Issue by mahesh-panchal** [evoldoers/biomake#27]
Hi, 

I couldn't find it in the documentation (or I just didn't understand it), but how can one pass slurm parameters to specific make rules. As I understand it currently, one passes sbatch parameters on the command line, but then all make targets are processed with those options. I don't see how one can say tell this rule to run with 4 cores and time of 2-00:00:00, while this other rule should be submitted with -n 16 and -t 3-12:00:00. Is there some prolog rule one can include with the make rule?

Regards,
Mahesh Binzer-Panchal.

**Comment by cmungall** [comment]
Hi Mahesh,

@ihh knows more about the slurm side of things. In general, to pass arguments to the batching system, you *should* be able to use `--qsub-args` or `--queue-args`.

However, it looks like this only works if your argument list has no spaces. If you try and pass an argument with a space, only the first token is consumed. This is true even when you try and quote the arguments.

I'll look into this some more.

**Comment by ihh** [comment]
Hi @mahesh-panchal 

You're correct, there was no way to pass slurm parameters (or any parameters) to individual make rules. Your suggestion of doing this via embedded Prolog goals is a good one, so I adopted it. You can now pass in arguments to `qsub` via the `QsubArgs` Prolog variable (works for SLURM's `sbatch` as well). Like so:

my_target: my_dependency { QsubArgs = '--cores-per-socket=4' }
    do_something >$@

Hope this helps, let us know how it works for you.
Ian

PS @cmungall moved your quoted-args bug report to #28

**Comment by ihh** [comment]
Minor syntax change (as of e85318d): `QsubArgs` must now be set in the target goal (makes more sense than setting it in the deps goal, since the dependencies are generally not built when the job is submitted to the queueing engine, and this was necessitating an unnecessary double test of the deps goal which might have other side effects)

Thus, the syntax of the example should now read

~~~~
my_target { QsubArgs = '--cores-per-socket=4' } : my_dependency
    do_something >$@
~~~~
