### ISSUE TITLE
Oddities with use of MD5 hashes instead of timestamps

### ISSUE THREAD

**Issue by cmungall** [evoldoers/biomake#36]
Makefile-simple:

```
a:
	echo a > $@

b: a
	echo b > $@
```

first iteration works as expected:

```
$ biomake -f Makefile-simple -H b
 echo a > a
Target b not materialized - build required
echo b > b
b built
```

changing the timestamp but leaving contents unmodified for upstream target:

```
$ touch a
$ biomake -f Makefile-simple -H b
 echo a > a
b is up to date
```

this isn't what I'd expected; there should be no need to re-execute the command to make `a`?

I am seeing similar behavior with `-C`. It seems to be regenerating the targets rather than simply recomputing the md5, which is what I believe is intended.

I can look into this further.

**Comment by ihh** [comment]
yeah, well spotted. When the file timestamp changes, biomake should recompute the hash (`md5_hash`) but _not_ ignore the validity condition (`md5_valid`). The two are stored in the same file, which is possibly a poor design decision, but the rationale is to avoid cluttering the filesystem. See e.g. [here](https://github.com/evoldoers/biomake/blob/master/t/ref/md5/.biomake/md5/hello_world) for examples

Somehow the code was failing to read the file when timestamps were stale, which kind of defeats the whole purpose of an MD5 timestamp. Really, the root problem was that there was no test! Crafting a test for this was a little devious since it requires calling biomake twice and subtly altering the recipe the second time (so test engine can tell if it's been re-run)
